name: maven build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Spring Boot 서버 중지
      - name: Stop Spring Boot Server
        run: sshpass -p "${{ secrets.PASSWORD }}" ssh -p 8122 api@123.100.174.98 "/home/api/.spring-server.sh stop"

      # 2. Maven을 사용해 프로젝트 빌드
      - name: Build with Maven
        run: sshpass -p "${{ secrets.PASSWORD }}" ssh -p 8122 api@123.100.174.98 "cd /home/api/git/user && mvn clean package"

      # 3. Spring Boot 서버 시작
      - name: Start Spring Boot Server
        run: sshpass -p "${{ secrets.PASSWORD }}" ssh -p 8122 api@123.100.174.98 "/home/api/.spring-server.sh start"
